name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: h-nago/github-actions-test

    - run: npm ci
    - run: npm test
    - uses: ./
      with:
        milliseconds: 1000
